<?php
$_str['pageTitle'] = 'Sistema de Saúde';

$_str['contentNav']['calendars'] = 'Calendários';
$_str['contentNav']['labels'] = 'Etiquetas';
$_str['contentNav']['procedures'] = 'Procedimentos';

$_str['lblDoSignUp'] = 'Cadastre-se';
$_str['nameCalendar']['0'] = 'Padrão';
$_str['nameCalendar']['1'] = 'Por Horários';
$_str['nameCalendar']['2'] = 'Pacientes Iletrados';
$_str['nameCalendar']['3'] = 'Pacientes Iletrados por horários';

$_str['gender'][0] = 'Masculino';
$_str['gender'][1] = 'Feminino';

$_str['civilState'][0] = 'Solteiro';
$_str['civilState'][1] = 'Casado';
$_str['civilState'][2] = 'Viúvo';
$_str['civilState'][3] = 'Divorciado';


$_str['state']['value'][0] = "AC"; $_str['state']['name'][0]="Acre";
$_str['state']['value'][1] = "AL"; $_str['state']['name'][1]="Alagoas";
$_str['state']['value'][2] = "AM"; $_str['state']['name'][2]="Amazonas";
$_str['state']['value'][3] = "AP"; $_str['state']['name'][3]="Amapá";
$_str['state']['value'][4] = "BA"; $_str['state']['name'][4]="Bahia";
$_str['state']['value'][5] = "CE"; $_str['state']['name'][5]="Ceará";
$_str['state']['value'][6] = "DF"; $_str['state']['name'][6]="Distrito Federal";
$_str['state']['value'][7] = "ES"; $_str['state']['name'][7]="Espirito Santo";
$_str['state']['value'][8] = "GO"; $_str['state']['name'][8]="Goiás";
$_str['state']['value'][9] = "MA"; $_str['state']['name'][9]="Maranhão";
$_str['state']['value'][10] = "MG"; $_str['state']['name'][10]="Minas Gerais";
$_str['state']['value'][11] = "MS"; $_str['state']['name'][11]="Mato Grosso do Sul";
$_str['state']['value'][12] = "MT"; $_str['state']['name'][12]="Mato Grosso";
$_str['state']['value'][13] = "PA"; $_str['state']['name'][13]="Pará";
$_str['state']['value'][14] = "PB"; $_str['state']['name'][14]="Paraíba";
$_str['state']['value'][15] = "PE"; $_str['state']['name'][15]="Pernambuco";
$_str['state']['value'][16] = "PI"; $_str['state']['name'][16]="Piauí";
$_str['state']['value'][17] = "PR"; $_str['state']['name'][17]="Paraná";
$_str['state']['value'][18] = "RJ"; $_str['state']['name'][18]="Rio de Janeiro";
$_str['state']['value'][19] = "RN"; $_str['state']['name'][19]="Rio Grande do Norte";
$_str['state']['value'][20] = "RO"; $_str['state']['name'][20]="Rondônia";
$_str['state']['value'][21] = "RR"; $_str['state']['name'][21]="Roraima";
$_str['state']['value'][22] = "RS"; $_str['state']['name'][22]="Rio Grande do Sul";
$_str['state']['value'][23] = "SC"; $_str['state']['name'][23]="Santa Catarina";
$_str['state']['value'][24] = "SE"; $_str['state']['name'][24]="Sergipe";
$_str['state']['value'][25] = "SP"; $_str['state']['name'][25]="São Paulo";
$_str['state']['value'][26] = "TO"; $_str['state']['name'][26]="Tocantins";


$_str['lblPrintLabel'] = 'Imprimir etiquetas';
$_str['signUpSuccess'] = 'Usuário cadastrado com sucesso! Aguarde a autorização dos administradores para acessar o sistema.';
$_str['lblEdit'] = 'Editar';
$_str['lblCancelEdition'] = 'Cancelar edição';
$_str['msgErrorUpdateUser'] = 'Não foi possível editar seus dados neste momento! Tente novamente mais tarde!';
$_str['msgErrorUpdatePatient'] = 'O usuário não pode ser editado! Tente novamente mais tarde!';
$_str['msgThePatientWasNotSelected'] = 'O usuário ainda não foi selecionado! Selecione agora na <a href="mainPage.php">página de seleção de usuários</a>!';
$_str['lblVisualizePatientData'] = 'Dados do usuário';
$_str['lblUnavailable'] = 'Não disponível';
$_str['lblSelect'] = 'Selecione';
$_str['msgSuccessAddPatient'] = 'Usuário adicionado!';
$_str['msgErrorSelectPatient'] = 'O usuário selecionado é inválido!';
$_str['msgErrorAddPatient'] = 'Ocorreu uma falha ao adicionar o usuário! Tente novamente mais tarde. Se o problema persistir, contate nosso suporte!';
$_str['lblAddress'] = 'Endereço';
$_str['lblStreet'] = 'Logradouro';
$_str['lblComplement'] = 'Número/complemento';
$_str['lblNeighboorhood'] = 'Bairro';
$_str['lblCity'] = 'Cidade';
$_str['lblState'] = 'Estado';
$_str['lblPhoneHome'] = 'Telefone de casa';
$_str['lblPhoneWork'] = 'Telefone do Trabalho';
$_str['lblPhoneCel'] = 'Celular';
$_str['lblPhones'] = 'Telefones';
$_str['lblRG'] = 'Doc. de identidade';
$_str['lblCivilState'] = 'Estado civil';
$_str['lblGender'] = 'Sexo';
$_str['lblBirthDate'] = 'Data de nascimento';
$_str['lblWeight'] = 'Peso';
$_str['lblHeight'] = 'Altura';
$_str['lblMotherName'] = 'Nome da mãe';
$_str['lblContactLevel'] = 'Nível de parentesco';
$_str['lblPersonalData'] = 'Dados Pessoais';
$_str['lblContactData'] = 'Dados do Contato';
$_str['lblCardSUS'] = 'Cartão SUS';
$_str['lblSelectUser'] = 'Selecionar Usuário';
$_str['lblAddUser'] = 'Adicionar Usuário';
$_str['lblMyData'] = 'Meu cadastro';
$_str['lblUsers'] = 'Usuários';
$_str['lblServices'] = 'Serviços';
$_str['lblAdd'] = 'Adicionar';
$_str['lblRestrictionsAndRecommendations'] = 'Adicionar recomendações e restrições';
$_str['lblQuantity'] = 'Quantidade';
$_str['lblAreYouSureYouWantToEraseThisMedicine'] = 'Você tem certeza que deseja apagar este medicamento?';
$_str['lblDosage'] = 'Dosagem';
$_str['lblEnter'] = 'Entrar';
$_str['lblClickToEdit...'] = 'Clique para editar...';
$_str['lblKeepMeLoggedIn'] = 'Mantenha-me conectado';
$_str['lblMedicine'] = 'Medicamento';
$_str['lblYouMustAcceptTerms'] = 'Você deve aceitar os termos de uso para se cadastrar!';
$_str['lblControlPanel'] = 'Painel de Controle'; 
$_str['lbltheIsNoUsersWaitingforAuthorization'] = 'Não há nenhum usuário esperando para ser autorizado';
$_str['lblAuthorizeUsers'] = 'Autorizar Usuários';
$_str['userUnauthorizedMessage'] = 'Seu usuário ainda não foi autorizado a acessar o sistema. Aguarde!';
$_str['lblWorkPlaces'] = 'Locais de Trabalho';
$_str['lblAddPlace'] = 'Adicionar local';
$_str['lblAddUnity'] = 'Adicionar unidade';
$_str['lblDownloadTheTerms'] = 'Download dos Termos de Uso';
$_str['lblIAcceptTheTerms'] = 'Eu aceito os termos de uso';
$_str['lblCRF'] = 'CRF';
$_str['lblEmail'] = 'E-mail';
$_str['lblPhone'] = 'Telefone';
$_str['lblSignUp'] = 'Cadastro';
$_str['lblAdminister'] = 'Administrar';
$_str['lblSystemAccess'] = 'Acesso ao Sistema';
$_str['lblCPF'] = 'CPF';
$_str['lblPassword'] = 'Senha';
$_str['lblHome'] = 'Início';
$_str['lblIncorrectData'] = 'Dados Incorretos';
$_str['defaultCalendarName'] = 'Calendário';
$_str['lblRename'] = 'Novo nome';
$_str['lblPrintCalendar'] = 'Imprimir Calendário';
$_str['lblAdd'] = 'Adicionar';
$_str['lblAddWorkPlace'] = 'Adicionar Local de Trabalho';
$_str['lblTypeTheNameOfYourUnity'] = 'Digite o nome de sua unidade';
$_str['lblLeave'] = 'Sair';
$_str['dateBeginBiggerThanDateEnd'] = 'A data inicial não pode ser menor do que a data final.';
$_str['headerCalendar']['0'] = 'Calendário Padrão';
$_str['headerConfigCalendar']['0'] = 'Configurações';
$_str['lblTypeMedicineDose'] = 'Digite a dosagem...';
$_str['lblTypeMedicine'] = 'Digite o medicamento...';
$_str['lblOk'] = 'Ok';
$_str['lblName'] = 'Nome';
$_str['lblMonth'] = 'Mês';
$_str['lblRecord'] = 'Registro';
$_str['lblDate'] = 'Data';
$_str['lblCalendar'] = 'Calendário';
$_str['lblUpdate'] = 'Salvar';
$_str['lblConfirm'] = 'Confirmar';
$_str['lblSaveAs'] = 'Salvar como';
$_str['lblPeriod'] = 'Período';
$_str['lblRestrictions'] = 'Restrições';
$_str['lblRecommendations'] = 'Recomendações';
$_str['lblPrint'] = 'Imprimir';
$_str['lblSave'] = 'Salvar';
$_str['lblOpen'] = 'Abrir';
$_str['lblUndo'] = 'Desfazer';
$_str['lblNew'] = 'Novo';
$_str['lblCreate'] = 'Criar';
$_str['lblChooseCalendarLayout'] = 'Escolha o modelo de calendário';
$_str['lblYouHaveReachedTheMaxNumberOfSchedules'] = 'Você atingiu o número máximo de horários.';
$_str['lblMedicine'] = 'Medicamento';
$_str['lblDose'] = 'Dose';
$_str['lblDoses'] = 'Doses';
$_str['lblSchedule'] = 'Horários';
$_str['lblImages'] = 'Imagens';
$_str['lblNumbers'] = 'Números';
$_str['lblTime'] = 'Horário';
$_str['lblSaveSchedule'] = 'Salvar';
$_str['lblCancel'] = 'Cancelar';
$_str['lblMedicineName'] = 'Nome do medicamento';
$_str['deleteCalendarWarning'] = 'Você tem certeza que deseja deletar \'%s\'?';
$_str['lblSixInSixHours'] = 'De 6 em 6 horas';
$_str['defaultLabelName'] = 'Label';

$_str['scheduleButton'] = 'Alterar';
$_str['scheduleToAll'] = 'Desejo aplicar este horário para todos os dias.';
$_str['medicineToAll'] = 'Desejo aplicar este medicamento para todos os horários posteriores.';
$_str['medicineButton'] = 'Alterar';
$_str['lblMedicineUpdate'] = 'Salvar';
$_str['lblMedicineLabel'] = 'Etiqueta';
$_str['lblSelectedLabel'] = 'Etiqueta selecionada';
$_str['lblChooseDoseImage'] = 'Escolha uma imagem para o medicamento';
$_str['lblSelectedDoseImage'] = 'Imagem selecionada';
$_str['ChooseDoseImageToAll'] = 'Desejo aplicar esta imagem para todos os medicamentos seguintes.';
$_str['lblMidnight'] = 'Meia-noite';
$_str['lblNoon'] = 'Meio-dia';
$_str['lblPeriodOfUse'] = 'Período de uso previsto: ';

$_str['month'][1] = 'Janeiro';
$_str['month'][2] = 'Fevereiro';
$_str['month'][3] = 'Março';
$_str['month'][4] = 'Abril';
$_str['month'][5] = 'Maio';
$_str['month'][6] = 'Junho';
$_str['month'][7] = 'Julho';
$_str['month'][8] = 'Agosto';
$_str['month'][9] = 'Setembro';
$_str['month'][10] = 'Outubro';
$_str['month'][11] = 'Novembro';
$_str['month'][12] = 'Dezembro';

$_str['week'][1] = 'Domingo';
$_str['week'][2] = 'Segunda';
$_str['week'][3] = 'Terça';
$_str['week'][4] = 'Quarta';
$_str['week'][5] = 'Quinta';
$_str['week'][6] = 'Sexta';
$_str['week'][7] = 'Sábado';

$_str['lblDawn'] = 'Madrugada';
$_str['lblMorning'] = 'Manhã';
$_str['lblAfternoon'] = 'Tarde';
$_str['lblNight'] = 'Noite';

$_str['state']['AC'] = 'AC';
$_str['state']['AL'] = 'AL';
$_str['state']['AP'] = 'AP';
$_str['state']['AM'] = 'AM';
$_str['state']['BA'] = 'BA';
$_str['state']['CE'] = 'CE';
$_str['state']['DF'] = 'DF';
$_str['state']['ES'] = 'ES';
$_str['state']['GO'] = 'GO';
$_str['state']['MA'] = 'MA';
$_str['state']['MT'] = 'MT';
$_str['state']['MS'] = 'MS';
$_str['state']['MG'] = 'MG';
$_str['state']['PR'] = 'PR';
$_str['state']['PB'] = 'PB';
$_str['state']['PA'] = 'PA';
$_str['state']['PE'] = 'PE';
$_str['state']['PI'] = 'PI';
$_str['state']['RJ'] = 'RJ';
$_str['state']['RN'] = 'RN';
$_str['state']['RS'] = 'RS';
$_str['state']['RO'] = 'RO';
$_str['state']['RR'] = 'RR';
$_str['state']['SC'] = 'SC';
$_str['state']['SE'] = 'SE';
$_str['state']['SP'] = 'SP';
$_str['state']['TO'] = 'TO';
				
?>
